apiVersion: v1
kind: Service
metadata:
  name: graphql-gateway-service
  namespace: campus-connect
  labels:
    app: graphql-gateway
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3004
      protocol: TCP
  selector:
    app: graphql-gateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql-gateway-deployment
  namespace: campus-connect
  labels:
    app: graphql-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graphql-gateway
  template:
    metadata:
      labels:
        app: graphql-gateway
    spec:
      containers:
        - name: graphql-app
          image: vipul710/graphql-gateway:latest
          ports:
            - containerPort: 3004
          env:
            - name: USS_URL
              value: "http://user-social-service:80"
            - name: EMS_URL
              value: "http://event-management-service:80"
            - name: DRS_URL
              value: "http://discovery-recommendation-service:80"
          resources:
            limits:
              cpu: "300m"
              memory: "384Mi"
